### ISSUE TITLE
Shader breaks when applied to a material that goes horizontal

### ISSUE THREAD

**Issue by ckusellagussin** [omid3098/Unity-URP-GlassShader#4]
![image](https://user-images.githubusercontent.com/14876536/234281291-f9854dbb-9113-4520-b19d-ec051972f01d.png)
Pretty hard to explain it but I don't know why this issue happens.

**Comment by omid3098** [comment]
It also is hard to figure out how your scene is set up and where the glass shader is!
If the shader is applied to the black side of the screen and you are referring to the bright part at the end, the reason is reflection which you can disable it. If it is not the case, please try to record a video or provide more details on what you are trying to do, what you have done to do that, what it looks like and what it should look like.
or a way to reproduce this behavior.
